name: serverless deployment

on:
  push:
    branches: [main]

jobs:
  deploy:

  runs-on: ubuntu-latest
  node-version: 14.x

  steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: User Node.js version ${{ node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ node-version }}
        cache: 'npm'
    - run: npm install -g serverless
    - run: > 
      serverless config credentials 
      --provider aws --key ${{ secret.aws_access_key_id }} 
      --secret ${{ secret.aws_secret_access_key }} 
      --profile serverlesss-framework-tutorial
    - run: serverless deploy
